---
- block:
  - name: Create upload remote directory
    file:
      path: "{{ upload_remote_dir }}"
      state: directory
      mode: 0755

  - name: Upload files
    copy:
      src: "files/"
      dest: "{{ upload_remote_dir }}/{{ role_name }}"

  - name: Unzip ansible src
    shell: tar -xvzf {{ upload_remote_dir }}/{{ role_name }}/ansible-{{ version }}.tar.gz -C {{ upload_remote_dir }}/{{ role_name }}

- name: Install
  shell: cd {{ upload_remote_dir }}/{{ role_name }} && chmod +x *.sh && ./install.sh {{ version }}
