---
- name: Create Service-Registry ConfigMap
  k8s: 
    host: '{{ k8s_auth_host }}'
    api_key: '{{ k8s_auth_api_key }}'
    state: present
    validate_certs: false
    definition: "{{ lookup('template', 'templates/configmap.yaml') | from_yaml }}"

- name: Create Service-Registry Service
  k8s: 
    host: '{{ k8s_auth_host }}'
    api_key: '{{ k8s_auth_api_key }}'
    state: present
    validate_certs: false
    definition: "{{ lookup('template', 'templates/service.yaml') | from_yaml }}"

- name: Create Service-Registry StatefulSet
  k8s: 
    host: '{{ k8s_auth_host }}'
    api_key: '{{ k8s_auth_api_key }}'
    state: present
    validate_certs: false
    definition: "{{ lookup('template', 'templates/statefulset.yaml') | from_yaml }}"

- name: Create Service-Registry Ingress
  k8s: 
    host: '{{ k8s_auth_host }}'
    api_key: '{{ k8s_auth_api_key }}'
    state: present
    validate_certs: false
    definition: "{{ lookup('template', 'templates/ingress.yaml') | from_yaml }}"