---
- name: Create Yaml directory
  file:
    path: "/tmp/backups/yaml"
    state: directory
    mode: 0755

- name: Backup Mics Pod 1 
  shell: kubectl get pod mics-{{name}}-1 -n {{ k8s_namespace }} -o yaml --export > /tmp/backups/yaml/mics-{{name}}-1.yaml

- name: Backup Mics Pod 2 
  shell: kubectl get pod mics-{{name}}-2 -n {{ k8s_namespace }} -o yaml --export > /tmp/backups/yaml/mics-{{name}}-2.yaml