apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  namespace: $NAMESPACE
data:
  # if you want to deploy n instances of eureka cluster,
  # you should set eureka_service_address: http://eureka-0.eureka:8761/eureka,...,http://eureka-(n-1).eureka:8761/eureka
  eureka_service_address: $EUREKA_SERVICE_ADDRESS

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: eureka
  namespace: $NAMESPACE
spec:
  serviceName: 'eureka'
  replicas: $EUREKA_REPLICAS
  selector:
    matchLabels:
      app: eureka # 符合目标的Pod有此标签
  template:
    metadata:
      labels:
        app: eureka  # Pod副本的标签
    spec:
      containers:
        - name: service-registry
          image: service-registry:$IMAGE_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: $NAMESPACE
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka
