---
- name: Create Yaml directory
  file:
    path: "/tmp/backups/yaml"
    state: directory
    mode: 0755

- name: Backup ConfigMap 
  shell: kubectl get configmap eureka-cm -n {{ k8s_namespace }} -o yaml --export > /tmp/backups/yaml/eureka-cm-configmap.yaml

- name: Backup StatefulSet 
  shell: kubectl get statefulset eureka -n {{ k8s_namespace }} -o yaml --export > /tmp/backups/yaml/eureka-statefulset.yaml