---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  namespace: {{ k8s_namespace }}
data:
  # if you want to deploy n instances of eureka cluster,
  # you should set eureka_service_address: http://eureka-0.eureka:8761/eureka,...,http://eureka-(n-1).eureka:8761/eureka
  eureka_service_address: {{ eureka_service_address }}
