---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: {{ k8s_namespace }}
spec:
  serviceName: 'eureka'
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: service-registry
        image: '{{ image }}:{{ image_tag}}'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address
