pipeline {
    agent any

    tools {
        git 'Default' 
    }

    triggers {
        cron('H/10 * * * *')
    }

    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }

    stages {
        stage('Prepare') {
            // input {
            //     message "Should we continue?"
            //     ok "Yes, we should."
            //     submitter "alice,bob"
            //     parameters {
            //         string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
            //     }
            // }

            steps { 
                echo "Hello, ${PERSON}, nice to meet you."
                sh 'git version'
            }
            post {
                always { 
                    echo 'I will always say Hello again!'
                }
            }
        }

        stage('Checkkout') {
            steps {
                echo 'Pull Source Code'
            }
        }

        stage('Build') {
            steps {
                echo 'Pull source code'
            }
        }

        stage("Push") {
            steps {
                echo 'Push to cloud'
            }
        }

        stage('Example') {
            steps {
                echo "Hello ${params.PERSON}"

                echo "Biography: ${params.BIOGRAPHY}"

                echo "Toggle: ${params.TOGGLE}"

                echo "Choice: ${params.CHOICE}"

                echo "Password: ${params.PASSWORD}"
            }
        }
    }
}