---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: {{ k8s_namespace }}
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
  - port: 8761
    name: eureka
  selector:
    app: eureka