---
- block:
  - name: Create directory
    file:
      path: "/tmp/rpms"
      state: directory
      mode: 0755

  - name: Upload rpm to Server
    copy:
      src: "files/packages/centos7"
      dest: "/tmp/rpms"

  - name: Upload ansible src file
    copy:
       src: "files/packages/ansible-{{ version }}.tar.gz"
       dest: "/tmp/ansible-{{ version }}.tar.gz"
  - name: Unzip ansible src
    shell: tar -xvzf /tmp/ansible-{{ version }}.tar.gz -C /tmp

- name: Install rpms
  shell: rpm -Uvh --force --nodeps /tmp/rpms/centos7/*rpm

- name: Install ansible
  shell: cd /tmp/ansible-{{ version }} && python setup.py install
