pipeline {
    agent any

    stages {
        

        // stage('Check') {
        //     steps {
        //         echo 'Check if Mysql is running'
        //         ansiblePlaybook(inventory: "${env.TOOL_HOME}/inventory/hosts", playbook: "${env.TOOL_HOME}/mysql-centos-playbook.yaml", tags: "checks", colorized: true)
        //     }
        // }

        stage('Install MySQL') {
            steps {
                sh "ansible-playbook -i ${env.TOOL_HOME}/inventory/hosts ${env.TOOL_HOME}/mysql-centos-playbook.yaml"
            }
            post {
                failure {
                    sh "ansible-playbook -i ${env.TOOL_HOME}/inventory/hosts ${env.TOOL_HOME}/mysql-centos-rollback.yaml"
                }
            }
        }
    }
}