---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '{{ resources_requests_storage }}'
  storageClassName: nfs-storage
