---
ansible_ssh_user: root

k8s_auth_host: 'https://10.38.2.12:6443'
k8s_auth_api_key: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkYXNoYm9hcmQtYWRtaW4tdG9rZW4tZng3enAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGFzaGJvYXJkLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNmNlYzEyZjktOThlZi00YTJlLWE1NTktZjM0YjJmZTUwNzZlIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmRhc2hib2FyZC1hZG1pbiJ9.uksg1LTqESXTlKQXKmlqstMhgIKQ5Z8LQaRVq_BGTsUhU3UPX3fTIDMiSMqtuU7zEZCCFkQOQh2mplLNChZEYrkhMqzXXaTWT0HKNuejv7XK6b655kga3x2EUXUovQBhTlHyH_W53fNTOn9zRJn2ofHQRDOEMXzW9fzWXR4HFum_BOTz7yCBgycmAaCKqSlO31Mh24KK3_UQEpMtrTYnXs0Wb5rM7ryunx_8F2rCHs3uHcruOi3b_TNKC6YSssNrsDfuRGY_TNsry5u4JpaoRysBtzga6cjffbTDF60LtOziID--7elz8HEMub7xqPQEMok-jCt7iO_N7oqSM197JA'
# default target namespace, can be replaced by vars
k8s_namespace: 'cloud'
# make sure docker registry can be access by docker
docker_registry: 192.168.33.10:5000
