- name: 读取ca证书stat信息
  stat: path="{{ base_dir }}/.cluster/ssl/etcd.pem"
  register: p
  connection: local
  run_once: true

- block:
    - name: 本地设置 bin 目录权限
      file: path={{ base_dir }}/plugins/cfssl state=directory mode=0755 recurse=yes
    - name: 创建etcd证书请求
      template: src=etcd-csr.json.j2 dest={{ base_dir }}/.cluster/ssl/etcd-csr.json
    - name: 创建 etcd证书和私钥
      shell: "cd {{ base_dir }}/.cluster/ssl && {{ base_dir }}/plugins/cfssl/cfssl gencert \
            -ca=ca.pem \
            -ca-key=ca-key.pem \
            -config=ca-config.json \
            -profile=kubernetes etcd-csr.json | {{ base_dir }}/plugins/cfssl/cfssljson -bare etcd"
  when: p.stat.isreg is not defined
  connection: local
  run_once: true

- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
    - "{{ bin_dir }}"
    - "{{ ca_dir }}"
    - "/etc/etcd/ssl"    # etcd 证书目录
    - "/var/lib/etcd"    # etcd 工作目录

- name: 下载etcd二进制文件
  copy: src={{ base_dir }}/plugins/etcd/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
    - etcd
    - etcdctl
  tags: upgrade_etcd

- name: 分发证书相关
  copy: src={{ base_dir }}/.cluster/ssl/{{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: "ca.pem", dest: "{{ ca_dir }}/ca.pem"}
    - {src: "etcd.pem", dest: "/etc/etcd/ssl/etcd.pem"}
    - {src: "etcd-key.pem", dest: "/etc/etcd/ssl/etcd-key.pem"}

- name: 创建etcd的systemd unit文件
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  tags: upgrade_etcd

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  ignore_errors: true
  tags: upgrade_etcd

- name: 以轮询的方式等待服务同步完成
  shell: "systemctl status etcd.service|grep Active"
  register: etcd_status
  until: '"running" in etcd_status.stdout'
  retries: 8
  delay: 8
  tags: upgrade_etcd
